server {
   server_name kittygramz.sytes.net;

   location / {
      proxy_pass http://127.0.0.1:9000;
   }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/alltasks.hopto.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/alltasks.hopto.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    server_name alltasks.hopto.org;

    location /api/ {
        proxy_pass http://127.0.0.1:8000;
    }

    location /admin/ {
        proxy_pass http://127.0.0.1:8000;
    }

    location / {
        root   /var/www/taski;
        index  index.html index.htm;
        try_files $uri /index.html;
    }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/alltasks.hopto.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/alltasks.hopto.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server {
    if ($host = alltasks.hopto.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot



    listen 80;
    server_name alltasks.hopto.org;
    return 404; # managed by Certbot


}server {
    if ($host = kittygramz.sytes.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


   server_name kittygramz.sytes.net;
    listen 80;
    return 404; # managed by Certbot


}
